baseURL = "https://chanjarster.github.io/"
languageCode = "zh-cn"
title = "颇忒脱的技术博客"
theme = "noteworthy"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Bookmarks"
  weight = 15
  identifier = "bookmarks"
  url = "/tags/收藏夹/"

[[menu.main]]
  name = "JVM"
  weight = 16
  identifier = "jvm"
  url = "/post/jvm/index-page"

[[menu.main]]
  name = "并发编程"
  weight = 17
  identifier = "concurrent-programming"
  url = "/post/concurrent-programming/index-page"

[[menu.main]]
  name = "MySQL"
  weight = 18
  identifier = "mysql"
  url = "/post/mysql/index-page"
  
[[menu.main]]
  name = "Go"
  weight = 19
  identifier = "go"
  url = "/tags/go/"

[[menu.main]]
  name = "GC"
  weight = 20
  identifier = "gc"
  url = "/tags/gc/"
  
[[menu.main]]
  name = "Kernel"
  weight = 21
  identifier = "kernel"
  url = "/tags/kernel/"

[[menu.main]]
  name = "Cheatsheet"
  weight = 30
  identifier = "cheat sheet"
  url = "/tags/cheatsheet/"

[[menu.main]]
  name = "Works"
  weight = 90
  identifier = "works"
  url = "https://github.com/chanjarster"

[[menu.main]]
  name = "Tags"
  weight = 100
  identifier = "tags"
  url = "/tags/"


[params]
  author = "颇忒脱"
  avatar = "/img/avatar2.jpg"
  
  github = "chanjarster"
  seotitle = "颇忒脱的技术博客"
  description = "颇忒脱的技术博客"
  paginate = 20

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true