baseURL = "https://chanjarster.github.io/"
languageCode = "zh-cn"
title = "颇忒脱的技术博客"
theme = "noteworthy"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Works"
  weight = 20
  identifier = "works"
  url = "https://github.com/chanjarster"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

[[menu.main]]
  name = "Bookmarks"
  weight = 15
  identifier = "bookmarks"
  url = "/tags/收藏夹/"

[[menu.main]]
  name = "JVM"
  weight = 16
  identifier = "jvm"
  url = "/post/jvm/index-page"

[[menu.main]]
  name = "并发编程"
  weight = 17
  identifier = "concurrent-programming"
  url = "/post/concurrent-programming/index-page"

[[menu.main]]
  name = "MySQL"
  weight = 18
  identifier = "mysql"

[[menu.main]]
  name = "Go"
  weight = 19
  identifier = "jvm"
  url = "/tags/go/"

[params]
  author = "颇忒脱"
  avatar = "/img/avatar2.jpg"
  
  github = "chanjarster"
  seotitle = "颇忒脱的技术博客"
  description = "颇忒脱的技术博客"
  paginate = 20